### ISSUE TITLE
Events ending at ≠ events spanning across midnight

### ISSUE THREAD

**Issue by ThomasMulot** [FossifyOrg/Calendar#341] opened 2024-10-07 18:30 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 12

### Affected device model

Nokia G50

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Make sure that the option "Show events spanning across midnight at the top bar" is checked in settings

1. Add a new event
2. set Start Time at 18:00 today
3. set End Time to 0:00 tomorrow
4. touch the checkmark in the top right corner to save the event

### Expected behavior

Events ending at midnight should not be shown as events spanning across midnight, if they do not span multiple days.

### Actual behavior

When "Show events spanning across midnight at the top bar" is checked, an event that ends at midnight is also showed in the top bar of the weekly view.

**Comment by Aga-C** [comment] 2024-10-07 19:10
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/255.

**Closed by Aga-C** 2024-10-07 19:10 UTC
Labels: bug, needs triage
