### ISSUE TITLE
Black on black and white on white text during widget configuration

### ISSUE THREAD

**Issue by nehemiagurl** [FossifyOrg/Calendar#59] opened 2024-01-11 11:46 UTC
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
During the widget configuration stage, the "show events happening" section has white on white text, and the options to select have black on black text (see screenshot)

**To Reproduce**
1. Go to Widgets>Fossify Calendar and add the Calendar event list widget
2. The widget configuration stage pops up. "Show events happening" is white on white.
3. Click on "Within the next 1 year"
4. The options are black on black.

**Expected behavior**
The colour of the text needs to be switched in both contexts. Black when there's a white background, white when there's a black background.

**Screenshots**
![Screenshot_20240111-114257_Calendar](https://github.com/FossifyOrg/Calendar/assets/109424320/52c456f6-51e7-49c7-8089-7917a82bcdcc)

**Device info (please complete the following information):**
 - Model: Galaxy A12
 - OS: Android 12
 - App version 1.0.2 (early access)

**Comment by Aga-C** [comment] 2024-01-11 12:14
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/41.

**Closed** 2024-01-11 12:14 UTC
Labels: duplicate
