### ISSUE TITLE
No "go to date" in event list view

### ISSUE THREAD

**Issue by madduck** [FossifyOrg/Calendar#403] opened 2024-12-17 08:37 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.0

### Affected Android/Custom ROM version

Android 15, GrapheneOS

### Affected device model

Pixel 7 Pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Select "Event List View"
2. Observe that there is no "Go to date" in the burger menu, and one also cannot tap on e.g. dates to get a dialog to pop up.

### Expected behavior

I expect there to be a "go to date" menu item, and I also kinda expect the dialog to pop up when I tap on a date in the event list:

![image](https://github.com/user-attachments/assets/5030b135-d103-481f-ab11-bc76225237e8)

### Actual behavior

There is no option to go to a date. Or I could not find one.

**Comment by Aga-C** [comment] 2024-12-17 08:49
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/120.

**Closed by Aga-C** 2024-12-17 08:49 UTC
Labels: bug, needs triage

**Comment by madduck** [comment] 2024-12-17 09:21
Sorry for the duplicate. I was looking for "go to", this issue diid not show up.
