### ISSUE TITLE
Hide yesterday's events in event list widget

### ISSUE THREAD

**Issue by flexagoon** [FossifyOrg/Calendar#195] opened 2024-03-30 10:43 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When using the event list widget with the timespan set to 1 day, you still see yesterday's events before current ones. Would be great to be able to hide them.

### Why do you want this feature?

I don't want to see what events I had yesterday and have to scroll down to see what I have today

**Comment by Aga-C** [comment] 2024-03-30 11:12
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/60.

**Closed** 2024-03-30 11:12 UTC
Labels: feature request, needs triage
