### ISSUE TITLE
Allow reordering calendars in main view

### ISSUE THREAD

**Issue by dabluecaboose** [FossifyOrg/Calendar#313] opened 2024-08-30 02:15 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I would like the ability to keep calendars in a custom order on the bottom of the main view.

### Why do you want this feature?

I currently have a calendar for my schedule, my wife's schedule, and my daughter's schedule.  Alphabetically, that puts mine last.  It would be nice to be able to put my calendar first in the list to make it easier to scroll through and enable/disable the other calendars without skipping over it.

### Additional information

Alternatively, feature #17 would allow me to at least rename my calendar to "_Name" or something of the sort to put it at the front of the list.

**Comment by Aga-C** [comment] 2024-08-30 04:48
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/169.

**Closed by Aga-C** 2024-08-30 04:48 UTC
Labels: feature request, needs triage
