### ISSUE TITLE
Material You Color Option for Widget

### ISSUE THREAD

**Issue by trbhlz** [FossifyOrg/Calendar#329] opened 2024-09-17 13:15 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It would be nice to have a material you colors option for the widget, for font color and also the background color.

### Why do you want this feature?

To have a native looking widget, i have to set the font color manual, everytime i change the wallpaper. And also the backgroundcolor doesn't fit either with the dark grey background.

### Additional information

<img src="https://github.com/user-attachments/assets/276609f9-c255-4aeb-8562-f727bf0f03d1" width="300" />

**Comment by Aga-C** [comment] 2024-09-17 13:39
It's a duplicate of https://github.com/FossifyOrg/General-Discussion/issues/146.

**Closed by Aga-C** 2024-09-17 13:39 UTC
Labels: feature request, needs triage
