### ISSUE TITLE
Clicking on a widget brings only to the daily view

### ISSUE THREAD

**Issue by Jokkaj** [FossifyOrg/Calendar#301] opened 2024-08-18 13:04 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Graphene os android 14

### Affected device model

Google pixel 5

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

When I create a widget that links to the calendar (for example, one of the breezy weather widgets that contains the day of the week) instead of opening normally on the weekly view like i left it fossify calendar opens up the daily view every time, this is pretty annoying and does not happen with any other calendar app.
This only happens with third party widgets with calendar link (like breezy weather) and not the original fossify calendar widgets 

### Expected behavior

It should keep my selected weekly view instead of forcing you to the daily view

### Actual behavior

It just boots you to daily view every time and the daily view stays selected even after exiting and reopening the app normally, so I have to re-set weekly view manually every time I open the calendar from any third party widget

**Comment by Aga-C** [comment] 2024-08-18 13:13
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/42.

**Closed by Aga-C** 2024-08-18 13:13 UTC
Labels: bug, needs triage
