### ISSUE TITLE
Calendar changes to Daily view as default setting

### ISSUE THREAD

**Issue by chanh2018** [FossifyOrg/Calendar#67] opened 2024-01-13 15:23 UTC
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**

**To Reproduce**
When choose Calendar to display in Google At the Glance (home screen), it always display Daily view
**Expected behavior**
Expecting the display follows setting in Calendar and not switching back to Daily view as "default"
**Screenshots**

**Device info (please complete the following information):**
 - Model: [e.g. Pixel 7]
 - OS: [e.g. Android 14]
 - App version [e.g. 6.28.1]
- Pixel 4A 5G
- Stock Android 14
-  Current Calendar version 1.0.2
**Additional context**

**Comment by Aga-C** [comment] 2024-01-13 15:32
Please fill out the template properly.

**Comment by Aga-C** [comment] 2024-01-26 08:41
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/102.

**Closed by Aga-C** 2024-01-26 08:41 UTC
Labels: duplicate
