### ISSUE TITLE
Swipe navigation issue in "Monthly and daily" view

### ISSUE THREAD

**Issue by thisisartman** [FossifyOrg/Calendar#362] opened 2024-10-25 20:23 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [x] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

version 1.0.3

### Affected Android/Custom ROM version

Crdroid 10.9

### Affected device model

Poco F4

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Set view to "Monthly and daily"
2. Swipe between months

### Expected behavior

Simple 50% swipe should ideally just take you to the next or previous month.

### Actual behavior

Swipe gets reset midway through the swipe erratically.

### Screenshots/Screen recordings

<img alt="Screenshot_20241026-013549_Calendar~2" src="https://github.com/user-attachments/assets/f2a91a6d-de78-4fbf-afdc-88b7c59028e1" width=195 />

https://github.com/user-attachments/assets/5deda315-0672-4b49-a346-d9bdfcfaed04

**Comment by Aga-C** [comment] 2024-10-25 20:40
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/153.

**Closed by Aga-C** 2024-10-25 20:40 UTC
Labels: bug, needs triage
