### ISSUE TITLE
Recurring events do not show notification

### ISSUE THREAD

**Issue by popogomo** [FossifyOrg/Calendar#189] opened 2024-03-26 15:07 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.2

### Affected Android/Custom ROM version

GrapheneOS

### Affected device model

Pixel 8 Pro

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

As mentioned in this issue tracker:

1. Create a recurring event
2. It will work fine the first time (the notification will show as expected)
3. However, consecutive events will not display a notification, the widget will show the event though. So the issue is in notification not being displayed for consecutive event.

The issue has been there forever, since Simple days.

Can you please look at this? Thanks.

### Expected behavior

Recurring events should display notification on each trigger

### Actual behavior

Only 1st event displays the notification, all other consecutive events do not display notifications

### Screenshots/Screen recordings

Its quite easy to reproduce as shown above but can upload a video if needed

### Additional information

Happens on other devices too like Samsung running TouchWiz

**Comment by Aga-C** [comment] 2024-03-26 15:48
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/26.

**Closed by Aga-C** 2024-03-26 15:48 UTC
Labels: bug, needs triage

**Comment by Aga-C** [comment] 2024-03-26 16:26
As long as the issue isn't closed, it's still relevant for us. Even if authors don't care anymore.
