### ISSUE TITLE
Add [years=xxxx] option for anniversaries and birthdays where xxxx is year of the event 

### ISSUE THREAD

**Issue by th1031** [FossifyOrg/Calendar#170] opened 2024-03-07 21:09 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

As an example, my father's birthday was July 1 1934. If I add the event to the calendar as Dad's birthday [years=1934] the calendar should calculate how old he will be on that date. The desired event will show on July 1, 2024 as Dad's birthday [90]

### Why do you want this feature?

It's a reminder of a person's age, the number of years they may have been married, or even the anniversary of starting work with some employer.  There are many uses for such a feature.

**Comment by Aga-C** [comment] 2024-03-07 21:27
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/20.

**Closed by Aga-C** 2024-03-07 21:27 UTC
Labels: feature request, needs triage
