### ISSUE TITLE
Spanish saturday translation

### ISSUE THREAD

**Issue by tuxArg** [FossifyOrg/Calendar#208] opened 2024-04-13 14:57 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 7a

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Set system spanish language.
Then go to monthly view

### Expected behavior

Saturday (Sábado) should be named "Sáb." or "S"

### Actual behavior

Saturday is named "Dom." (Domingo = Sunday)

### Screenshots/Screen recordings

<img alt="Screenshot_20240413-115137" src="https://github.com/FossifyOrg/Calendar/assets/42143259/b0365285-0af5-4997-8b96-154fef48bc90" width=600 />

**Comment by Aga-C** [comment] 2024-04-13 15:16
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/205.

**Closed** 2024-04-13 15:16 UTC
Labels: bug, needs triage
