### ISSUE TITLE
Renaming contacts doesn't rename birthday events

### ISSUE THREAD

**Issue by qwerty287** [FossifyOrg/Calendar#298] opened 2024-08-13 05:39 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 12

### Affected device model

-

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Add birthdays
2. Rename a contact with birthday

### Expected behavior

The name of the birthday event it synced with the contact name

### Actual behavior

Nothing changes at the event

**Comment by Aga-C** [comment] 2024-08-13 06:09
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/194.

**Closed by Aga-C** 2024-08-13 06:09 UTC
Labels: bug, needs triage
