### ISSUE TITLE
Pulling down while swiping left/right cancels the left/right swipe

### ISSUE THREAD

**Issue by K4LCIFER** [FossifyOrg/Calendar#192] opened 2024-03-26 22:46 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 6 Pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to monthly view
2. Swipe to the left or right partly so that you start the animation to switch months (don't lift your finger though)
3. While still holding your finger, pull down slightly
4. observe that the left/right swipe action cancels, and the update action starts to trigger

### Expected behavior

I would expect that, once the animation is triggered, it should lock-on to left/right motion, and ignore up/down motion and not cancel until you lift your finger.

### Actual behavior

When you drag down while swiping left or right, the left/right swipe animation cancels, and the update action begins.

### Screenshots/Screen recordings

https://github.com/SimpleMobileTools/Simple-Calendar/assets/7829231/e8f6a892-a369-4a33-8e21-7d8bbafc40f5

### Additional information

This came from https://github.com/SimpleMobileTools/Simple-Calendar/issues/2172 where the issue was ignored.

**Comment by Aga-C** [comment] 2024-03-27 06:12
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/153.

**Closed by Aga-C** 2024-03-27 06:12 UTC
Labels: bug, needs triage
