### ISSUE TITLE
Repeated events do not update properly when using "Update the selected occurrence only"

### ISSUE THREAD

**Issue by jfaure9** [FossifyOrg/Calendar#354] opened 2024-10-16 20:07 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14 / Lineage 21

### Affected device model

Samsung Galaxy S10e

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Create a repeated event.
2. Edit the first occurrence of the repeated event and change the date to a day for which there isn't an occurrence currently. 
3. On save, select "Update the selected occurrence only".

### Expected behavior

As "Update the selected occurrence only" has been selected, the selected occurrence should be *moved* to the new date instead of copied.

### Actual behavior

 A *new* occurrence is created on the selected day and the original occurrence is still there.

**Comment by Aga-C** [comment] 2024-10-16 20:30
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/138.

**Closed by Aga-C** 2024-10-16 20:30 UTC
Labels: bug, needs triage

**Comment by jfaure9** [comment] 2024-10-17 06:36
Oups sorry! I made a search in the existing issues but not with the right keywords apparently. Will #138 be fixed soon?
