### ISSUE TITLE
Enable CalDAV update in weekly view

### ISSUE THREAD

**Issue by dktzde** [FossifyOrg/Calendar#191] opened 2024-03-26 18:15 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

DivestOS 20 - Android 13

### Affected device model

Pixel 3 blueline

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1.) Settings; CalDAV; Enable pull-to-refresh from the top
2.) Use weekly view
3.) pull from the top - CalDAV Calender will not be synced

### Expected behavior

Should sync

### Actual behavior

Does not sync

### Additional information

I have tried all the other views. The CalDAV sync works in all other views without any problems.

**Comment by Aga-C** [comment] 2024-03-27 06:23
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/128.

**Closed by Aga-C** 2024-03-27 06:23 UTC
Labels: enhancement
