### ISSUE TITLE
Allow setting reminder AFTER start of event.

### ISSUE THREAD

**Issue by woheller69** [FossifyOrg/Calendar#306] opened 2024-08-25 12:22 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Allow setting reminder AFTER start of event.

### Why do you want this feature?

For whole day events (e.g. birthdays) I would not like to get a reminder at midnight or the day before, but e.g. 9:00am so I will not forget to call

**Comment by Aga-C** [comment] 2024-08-25 12:31
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/54.

**Closed by Aga-C** 2024-08-25 12:31 UTC
Labels: feature request, needs triage
