### ISSUE TITLE
View and edit mode for events

### ISSUE THREAD

**Issue by acitonic** [FossifyOrg/Calendar#210] opened 2024-04-15 15:29 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Is it possible to add a feature that opens existing events in a "viewing mode" with a nicer look and overview (has to be created), from which then you could press an edit button to make changes. 

There could be also a thing in the settings where you could switch between directly getting into edit mode or firstly into view mode.

Thanks in advance :)

### Why do you want this feature?

Often I just want to open events for the details, but not to edit them. I'd like a better stuctured and more compact view when opening existing events

**Comment by Aga-C** [comment] 2024-04-15 15:36
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/171.

**Closed by Aga-C** 2024-04-15 15:36 UTC
Labels: feature request, needs triage
