### ISSUE TITLE
Share/export email directly into a new calendar event

### ISSUE THREAD

**Issue by spectas** [FossifyOrg/Calendar#391] opened 2024-12-10 07:15 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I’d like Fossify Calendar to support creating calendar events using Android’s built-in Share function. When "sharing" an email from an email app like Thunderbird for Android/K-9 Mail, the app could use the email subject as the event title and the email body (including sender, receiver, and date info) as the event description.

### Why do you want this feature?

Manually creating calendar events from emails is time-consuming. With Android’s Share function, apps like Nextcloud Notes and Joplin create complete notes from shared emails. Similar support in Fossify Calendar would simplify adding events directly from emails.

**Comment by Aga-C** [comment] 2024-12-10 08:17
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/180.

**Closed by Aga-C** 2024-12-10 08:17 UTC
Labels: feature request, needs triage

**Comment by spectas** [comment] 2024-12-10 22:29
Hi @Aga-C , I understand that it looks like a duplicate, but I'd like to ask to reconsider. The other request was very general, whereas this one addresses one standard API of Android, the "Share" function, which works with most apps, but is not implemented in Fossify calendar. Email apps do have an export API, and it's working great. Last I humble ask to reconsider your assessment of how useful it is. Like me I am sure that many people receive and email and just want to add a calendar event as simple as possible, since it's a standard procedure. Marking the mail text, copying, opening the calendar, creating an event and then pasting the text - is manageable I agree, but could be so much easier. I how I could explain a bit better what I meant before. Thanks

**Comment by Aga-C** [comment] 2024-12-11 07:03
It's still a duplicate, even if you provided here more details. You can add your remarks in the original issue and we can consider reopening it.
