### ISSUE TITLE
Add a multi weeks view design

### ISSUE THREAD

**Issue by Vucumpra** [FossifyOrg/Calendar#334] opened 2024-09-26 07:36 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Hello,
Will be nice if you add a multiweek view : 
Multi-week view have the same design of monthly view but the current day is always on top.

### Why do you want this feature?

This feature provide more screen space for next events, so more next days displayed !

### Additional information

Next/Previous button will refresh the screen week by week

**Comment by Aga-C** [comment] 2024-09-26 07:55
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/155.

**Closed by Aga-C** 2024-09-26 07:55 UTC
Labels: feature request, needs triage
