### ISSUE TITLE
Incorrect day of the week in Spanish Monthly view

### ISSUE THREAD

**Issue by Guuustav** [FossifyOrg/Calendar#328] opened 2024-09-17 07:35 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14 (OneUI 

### Affected device model

Samsung Galaxy S23 Ultra

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Click Grid icon (top toolbar), select Monthly or Monthly and daily views. Only in these two views is the name of Saturday incorrectly written as Dom. which is the abbreviation for "Domingo" in Spanish. 

### Expected behavior

It should say "S" for "Sábado" (Saturday in Spanish). In the other views the abbreviation "Sab." for "Sábado" is correct.

### Actual behavior

Saturday incorrectly written as Dom. which is the abbreviation for "Domingo" in Spanish. 

### Screenshots/Screen recordings

![Fossify](https://github.com/user-attachments/assets/7b117836-5ade-42c7-8966-0dedba7337ff)

### Additional information

Thanks for your gorgeous job.

**Comment by Aga-C** [comment] 2024-09-17 08:13
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/205.

**Closed by Aga-C** 2024-09-17 08:13 UTC
Labels: bug, needs triage
