### ISSUE TITLE
dublicate event if edited

### ISSUE THREAD

**Issue by krzemyczek** [FossifyOrg/Calendar#256] opened 2024-06-18 14:20 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

GrapheneOS 14 (AP2A.240605.024)

### Affected device model

Pixel 6a

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Create repeated event
2. Edit date and select "Update the selected occurrence only"
3. See duplicated event (one with previous date, and other one with new one)

### Expected behavior

Only event with new date

### Actual behavior

Duplicate event with new and old date

### Screenshots/Screen recordings

<img alt="Screenshot_20240618-161431" src="https://github.com/FossifyOrg/Calendar/assets/81762967/10f7954d-b588-4aa5-9f6c-a8e9ace44bfb" width=180 />
<img alt="Screenshot_20240618-161449" src="https://github.com/FossifyOrg/Calendar/assets/81762967/81a60d63-150f-47ad-97db-c020938c00ce" width=180 />
<img alt="Screenshot_20240618-161459" src="https://github.com/FossifyOrg/Calendar/assets/81762967/d3238a4d-5c4c-4939-9524-38b933b2f0e9" width=180 />
<img alt="Screenshot_20240618-161533" src="https://github.com/FossifyOrg/Calendar/assets/81762967/e745b76f-c698-415b-9d98-24c185ea72ba" width=180 />
<img alt="Screenshot_20240618-161508" src="https://github.com/FossifyOrg/Calendar/assets/81762967/632e3419-dccc-430a-958c-a7fb44230bca" width=180 />

**Comment by Aga-C** [comment] 2024-06-18 15:02
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/138.

**Closed by Aga-C** 2024-06-18 15:02 UTC
Labels: bug, needs triage
