### ISSUE TITLE
Allow Creating Appointment when Notifications are disabled

### ISSUE THREAD

**Issue by franz-sw** [FossifyOrg/Calendar#345] opened 2024-10-10 15:17 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When app notifications are disabled, users are unable to create new calendar appointments. A dialog appears prompting the user to either dismiss the action (which prevents the event from being created) or enable notifications. There is no option to proceed with creating the event without enabling notifications.

### Why do you want this feature?

I don't want notifications at all.

**Comment by Aga-C** [comment] 2024-10-10 15:35
It's a duplicate of https://github.com/FossifyOrg/Calendar/issues/220.

**Closed by Aga-C** 2024-10-10 15:35 UTC
Labels: feature request, needs triage
